services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app
      - ../../data:/app/data
      - ../../tools:/app/tools
      - chroma_data:/app/chroma_db
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app:/app/src
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 400s

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  chroma_data:
